name = "TrenchPack"
prefix = "tg"
author = "Trenchgun"

version = "2.0.0"
key_name = "{{prefix}}_{{version}}"
sig_name = "{{prefix}}_{{version}}"
modname = "trenchpack"

skip = [
	"oc"
]

releasebuild = [
    "@zip trenchpack_{{version}}"
]

exclude = [
	"*.psd",
	"*.png",
	"*.tga"
]